import { Grid } from "@chakra-ui/react"
import { BookItem } from "./BookItem"

export const BookGrid = () => {
  const tmpBookContents = {
    imageUrl: "",
    title: "タイトルです",
    bookId: "alice",
  }
  return (
    <Grid
      templateColumns="repeat(auto-fill, 150px)"
      justifyContent="center"
      gap={6}
      mx="auto"
    >
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
      <BookItem
        bookId={tmpBookContents.bookId}
        title={tmpBookContents.title}
        imageUrl={tmpBookContents.imageUrl}
      ></BookItem>
    </Grid>
  )
}
